### ISSUE TITLE
`AttributeError` for `_close_handle` on `close()` of `ISOReadFS` with non-seekable file handle

### ISSUE THREAD

**Issue by dcoshea** [althonos/fs.archive#11]
If I create an instance of `fs.archive.isofs.ISOReadFS` by passing it a file handle `f` where `f.seekable()` is False, then when I subsequently call `ISOReadFS.close()` I get:

```
[...]
    [...].close()
  File "[...]/site-packages/fs/archive/base.py", line 193, in close
    if self._close_handle:
AttributeError: 'ISOReadFS' object has no attribute '_close_handle'
```

I note that `ArchiveReadFS.__init__()` includes:

```
        elif hasattr(handle, 'read'):
            # Create the readable fs if the handle is readable
            if handle.readable() and handle.seekable():
                self._close_handle = options.get('close_handle', True)
                self._handle = handle

        else:
            raise errors.CreateFailed("cannot use {}".format(handle))
```

so I guess that passing a non-seekable handle results in `_close_handle` and `_handle` not being set.  Perhaps the intent was that an exception should be thrown if the file is non-readable or non-seekable rather than just leaving some attributes unset?  I was still able to read a file from the `ISOReadFS` though, so it seems like perhaps it doesn't really need a seekable handle.

For now I'm giving it a seekable handle anyway (by using a `io.BytesIO` wrapper) as a workaround.

Seen with these package versions:

```
fs==2.4.15
fs.archive==0.7.1
pycdlib==1.12.0
```

**Comment by althonos** [comment]
Hi @dcoshea , thanks for the bug report! 

Yes, the final `CreateFailed` exception should be thrown here, I'll make a patch release for this.

I'm not sure how you managed to read a file from the `ISOReadFS` still, because in theory `pycdlib` (which handles the ISO format) does a lot of seeking, even when it's just opening ISO to read the headers!

**Comment by althonos** [comment]
Should be fixed in `v0.7.2`.

**Comment by dcoshea** [comment]
> Yes, the final `CreateFailed` exception should be thrown here, I'll make a patch release for this.

Thanks!

> I'm not sure how you managed to read a file from the `ISOReadFS` still, because in theory `pycdlib` (which handles the ISO format) does a lot of seeking, even when it's just opening ISO to read the headers!

Sorry, I have no idea, but I assume it's doing some buffering because merely opening the .iso file is quite slow, as is opening from it.  I wrote this small test program, which is designed to be passed the path to a FreeDOS 1.3 rc4 `FD13-LiveCD.zip` file:

```
import hashlib
import sys
import time

import fs.archive.isofs
import fs.osfs
import fs.subfs
import fs.zipfs

time0 = time.time()

def log(message):
    print(f"{time.time() - time0:f} {message}")

log("Opening root filesystem")
root_fs = fs.osfs.OSFS("/")

log("Opening outer .zip file")
outer_zip_fs = fs.zipfs.ReadZipFS(root_fs.open(sys.argv[1], "rb"))

log("Opening .iso file")
iso_file = outer_zip_fs.open("FD13LIVE.iso", "rb")
assert not iso_file.seekable()
iso_fs = fs.archive.isofs.ISOReadFS(iso_file)

log("Opening inner .zip file")
inner_zip_fs = fs.zipfs.ReadZipFS(iso_fs.open("packages/base/fdapm.zip", "rb"))

log("Opening sub-directory")
sub_fs = fs.subfs.SubFS(inner_zip_fs, "BIN/")

log("Opening file")
with sub_fs.open("FDAPM.COM", "rb") as file_handle:
    data = file_handle.read()
    assert b"*UPX!" in data

log("Done")
```

When I run it, I get:
```
0.000004 Opening root filesystem
0.000827 Opening outer .zip file
0.001557 Opening .iso file
1.978690 Opening inner .zip file
5.699245 Opening sub-directory
5.699375 Opening file
6.920082 Done
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "[...]/site-packages/fs/base.py", line 116, in __del__
  File "[...]/site-packages/fs/archive/base.py", line 193, in close
AttributeError: 'ISOReadFS' object has no attribute '_close_handle'
```

I suppose pycdlib needs buffering to handle the case where we might modify the .iso file, so maybe it uses that for pure read cases too?  I took a quick look at the code but it wasn't obvious to me what it might be doing here.

My package versions are still as I mentioned previously, I haven't grabbed your change yet.

**Comment by dcoshea** [comment]
I can verify that the fix works in 0.7.2 though - I can't pass a non-seekable file handle.

**Comment by althonos** [comment]
Oh ok, I see! I think this may be a bug in `ReadZipFS` because the file object **is** seekable, but it looks like the `seekable` method was not patched and would still return `False`. In consequence, you were passing a file that was indeed seekable, and since `pycdlib` never calls `seekable` but `seek` directly this is how you got it to work.

**Comment by althonos** [comment]
And the reason it was so slow is because the `_ZipExtFile` object is seekable through emulation, so whenever a `seek` is done the file is reopened and read until the requested position, which is not really optimal.
